
  import IntroductionToTheNeverFapDeluxeGuide from '../content/articles/IntroductionToTheNeverFapDeluxeGuide';
import MyPersonalPornRecoveryJourney from '../content/articles/MyPersonalPornRecoveryJourney';
import TheFiveFundamentalPrinciplesOfNeverFap from '../content/articles/TheFiveFundamentalPrinciplesOfNeverFap';
import TheOneRuleOfNeverFap from '../content/articles/TheOneRuleOfNeverFap';
import WhyamIAPornAddict from '../content/articles/WhyamIAPornAddict';
import WhatMakesNeverFapSoDifferent from '../content/articles/WhatMakesNeverFapSoDifferent';
import PayingTheNeverFapMaintenanceTax from '../content/articles/PayingTheNeverFapMaintenanceTax';
import TheImportanceOfMeditationForPornAddiction from '../content/articles/TheImportanceOfMeditationForPornAddiction';
import EverythingIsAChoice from '../content/articles/EverythingIsAChoice';
import TheFivePrinciplesOfNeverFapAsTheyRelateToMyLife from '../content/articles/TheFivePrinciplesOfNeverFapAsTheyRelateToMyLife';
import YouAlwaysHaveTimeForYourMentalHealth from '../content/articles/YouAlwaysHaveTimeForYourMentalHealth';
import CreatingYourFirstNeverFapSchedule from '../content/articles/CreatingYourFirstNeverFapSchedule';
import TheNeverFapStateOfMind from '../content/articles/TheNeverFapStateOfMind';
import YourPornAddictionIsNotWhoYouAre from '../content/articles/YourPornAddictionIsNotWhoYouAre';
import TheEasiestWayToIdentifyAJudgement from '../content/articles/TheEasiestWayToIdentifyAJudgement';
import TheUltimateAimOfNeverFapDeluxePractices from '../content/articles/TheUltimateAimOfNeverFapDeluxePractices';
import WhyYouShouldNeverDependOnYourEmotions from '../content/articles/WhyYouShouldNeverDependOnYourEmotions';
import TheEasiestWayToNotTakeOurEmotionsPersonally from '../content/articles/TheEasiestWayToNotTakeOurEmotionsPersonally';
import WhatItFeelsLikeNotToBeAddictedToPorn from '../content/articles/WhatItFeelsLikeNotToBeAddictedToPorn';
import WhatIsNeverFap from '../content/articles/WhatIsNeverFap';

  const ArticlesScreens = new Map();

  export const INTRODUCTIONTOTHENEVERFAPDELUXEGUIDE_SCREEN = 'navigation.IntroductionToTheNeverFapDeluxeGuideScreen';
export const MYPERSONALPORNRECOVERYJOURNEY_SCREEN = 'navigation.MyPersonalPornRecoveryJourneyScreen';
export const THEFIVEFUNDAMENTALPRINCIPLESOFNEVERFAP_SCREEN = 'navigation.TheFiveFundamentalPrinciplesOfNeverFapScreen';
export const THEONERULEOFNEVERFAP_SCREEN = 'navigation.TheOneRuleOfNeverFapScreen';
export const WHYAMIAPORNADDICT_SCREEN = 'navigation.WhyamIAPornAddictScreen';
export const WHATMAKESNEVERFAPSODIFFERENT_SCREEN = 'navigation.WhatMakesNeverFapSoDifferentScreen';
export const PAYINGTHENEVERFAPMAINTENANCETAX_SCREEN = 'navigation.PayingTheNeverFapMaintenanceTaxScreen';
export const THEIMPORTANCEOFMEDITATIONFORPORNADDICTION_SCREEN = 'navigation.TheImportanceOfMeditationForPornAddictionScreen';
export const EVERYTHINGISACHOICE_SCREEN = 'navigation.EverythingIsAChoiceScreen';
export const THEFIVEPRINCIPLESOFNEVERFAPASTHEYRELATETOMYLIFE_SCREEN = 'navigation.TheFivePrinciplesOfNeverFapAsTheyRelateToMyLifeScreen';
export const YOUALWAYSHAVETIMEFORYOURMENTALHEALTH_SCREEN = 'navigation.YouAlwaysHaveTimeForYourMentalHealthScreen';
export const CREATINGYOURFIRSTNEVERFAPSCHEDULE_SCREEN = 'navigation.CreatingYourFirstNeverFapScheduleScreen';
export const THENEVERFAPSTATEOFMIND_SCREEN = 'navigation.TheNeverFapStateOfMindScreen';
export const YOURPORNADDICTIONISNOTWHOYOUARE_SCREEN = 'navigation.YourPornAddictionIsNotWhoYouAreScreen';
export const THEEASIESTWAYTOIDENTIFYAJUDGEMENT_SCREEN = 'navigation.TheEasiestWayToIdentifyAJudgementScreen';
export const THEULTIMATEAIMOFNEVERFAPDELUXEPRACTICES_SCREEN = 'navigation.TheUltimateAimOfNeverFapDeluxePracticesScreen';
export const WHYYOUSHOULDNEVERDEPENDONYOUREMOTIONS_SCREEN = 'navigation.WhyYouShouldNeverDependOnYourEmotionsScreen';
export const THEEASIESTWAYTONOTTAKEOUREMOTIONSPERSONALLY_SCREEN = 'navigation.TheEasiestWayToNotTakeOurEmotionsPersonallyScreen';
export const WHATITFEELSLIKENOTTOBEADDICTEDTOPORN_SCREEN = 'navigation.WhatItFeelsLikeNotToBeAddictedToPornScreen';
export const WHATISNEVERFAP_SCREEN = 'navigation.WhatIsNeverFapScreen';

  ArticlesScreens.set(INTRODUCTIONTOTHENEVERFAPDELUXEGUIDE_SCREEN, IntroductionToTheNeverFapDeluxeGuide);
ArticlesScreens.set(MYPERSONALPORNRECOVERYJOURNEY_SCREEN, MyPersonalPornRecoveryJourney);
ArticlesScreens.set(THEFIVEFUNDAMENTALPRINCIPLESOFNEVERFAP_SCREEN, TheFiveFundamentalPrinciplesOfNeverFap);
ArticlesScreens.set(THEONERULEOFNEVERFAP_SCREEN, TheOneRuleOfNeverFap);
ArticlesScreens.set(WHYAMIAPORNADDICT_SCREEN, WhyamIAPornAddict);
ArticlesScreens.set(WHATMAKESNEVERFAPSODIFFERENT_SCREEN, WhatMakesNeverFapSoDifferent);
ArticlesScreens.set(PAYINGTHENEVERFAPMAINTENANCETAX_SCREEN, PayingTheNeverFapMaintenanceTax);
ArticlesScreens.set(THEIMPORTANCEOFMEDITATIONFORPORNADDICTION_SCREEN, TheImportanceOfMeditationForPornAddiction);
ArticlesScreens.set(EVERYTHINGISACHOICE_SCREEN, EverythingIsAChoice);
ArticlesScreens.set(THEFIVEPRINCIPLESOFNEVERFAPASTHEYRELATETOMYLIFE_SCREEN, TheFivePrinciplesOfNeverFapAsTheyRelateToMyLife);
ArticlesScreens.set(YOUALWAYSHAVETIMEFORYOURMENTALHEALTH_SCREEN, YouAlwaysHaveTimeForYourMentalHealth);
ArticlesScreens.set(CREATINGYOURFIRSTNEVERFAPSCHEDULE_SCREEN, CreatingYourFirstNeverFapSchedule);
ArticlesScreens.set(THENEVERFAPSTATEOFMIND_SCREEN, TheNeverFapStateOfMind);
ArticlesScreens.set(YOURPORNADDICTIONISNOTWHOYOUARE_SCREEN, YourPornAddictionIsNotWhoYouAre);
ArticlesScreens.set(THEEASIESTWAYTOIDENTIFYAJUDGEMENT_SCREEN, TheEasiestWayToIdentifyAJudgement);
ArticlesScreens.set(THEULTIMATEAIMOFNEVERFAPDELUXEPRACTICES_SCREEN, TheUltimateAimOfNeverFapDeluxePractices);
ArticlesScreens.set(WHYYOUSHOULDNEVERDEPENDONYOUREMOTIONS_SCREEN, WhyYouShouldNeverDependOnYourEmotions);
ArticlesScreens.set(THEEASIESTWAYTONOTTAKEOUREMOTIONSPERSONALLY_SCREEN, TheEasiestWayToNotTakeOurEmotionsPersonally);
ArticlesScreens.set(WHATITFEELSLIKENOTTOBEADDICTEDTOPORN_SCREEN, WhatItFeelsLikeNotToBeAddictedToPorn);
ArticlesScreens.set(WHATISNEVERFAP_SCREEN, WhatIsNeverFap);

  export default ArticlesScreens;

  